/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Executives;

import Business.Business;
import Business.Customers.CustomersSeller;
import Business.Customers.CustomersSellerDirectory;
import Business.Executives.ExecutiveCases;
import Business.Executives.ExecutiveCasesDirectory;
import javax.swing.JPanel;

/**
 *
 * @author bindupagad
 */
public class AssignedCasesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignedCasesJPanel
     */
    JPanel workAreaMain;
    Business business;
        ExecutiveCasesDirectory exeCasesDirectory;
        CustomersSellerDirectory custSellerDirectory;
        ExecutiveCases myCase;
        

    
    public AssignedCasesJPanel(JPanel workAreaMain, Business business, ExecutiveCases exeCase) {
        initComponents();
        this.workAreaMain = workAreaMain;
        this.business = business;
        exeCasesDirectory = business.getExeCasesDirectory();
        custSellerDirectory = business.getCustomersSellerDirectory();
        this.myCase = exeCase;
        showDetailsofCase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        txtManufactureYear = new javax.swing.JTextField();
        lblTransmission = new javax.swing.JLabel();
        lblMilesDriven = new javax.swing.JLabel();
        lblFuelType = new javax.swing.JLabel();
        txtMilesDriven = new javax.swing.JTextField();
        lblAccidents = new javax.swing.JLabel();
        txtCarCompany = new javax.swing.JTextField();
        txtAccidents = new javax.swing.JTextField();
        lblCarCompany = new javax.swing.JLabel();
        lblCostPrice = new javax.swing.JLabel();
        txtSellPrice = new javax.swing.JTextField();
        lblCarModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtFuel = new javax.swing.JTextField();
        txtTransmission = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtComments = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnPostComments = new javax.swing.JButton();

        jLabel9.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(73, 84, 90));
        jLabel9.setText("Manufacture Year");

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtManufactureYear.setBackground(new java.awt.Color(248, 248, 249));

        lblTransmission.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblTransmission.setForeground(new java.awt.Color(73, 84, 90));
        lblTransmission.setText("Transmission");

        lblMilesDriven.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblMilesDriven.setForeground(new java.awt.Color(73, 84, 90));
        lblMilesDriven.setText("Miles Driven");

        lblFuelType.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblFuelType.setForeground(new java.awt.Color(73, 84, 90));
        lblFuelType.setText("Fuel Type");

        txtMilesDriven.setBackground(new java.awt.Color(248, 248, 249));

        lblAccidents.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblAccidents.setForeground(new java.awt.Color(73, 84, 90));
        lblAccidents.setText("No. of Accidents");

        txtCarCompany.setBackground(new java.awt.Color(248, 248, 249));
        txtCarCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarCompanyActionPerformed(evt);
            }
        });

        txtAccidents.setBackground(new java.awt.Color(248, 248, 249));

        lblCarCompany.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblCarCompany.setForeground(new java.awt.Color(73, 84, 90));
        lblCarCompany.setText("Company");

        lblCostPrice.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblCostPrice.setForeground(new java.awt.Color(73, 84, 90));
        lblCostPrice.setText("Selling Price");

        txtSellPrice.setBackground(new java.awt.Color(248, 248, 249));

        lblCarModel.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblCarModel.setForeground(new java.awt.Color(73, 84, 90));
        lblCarModel.setText("Car Model");

        txtModel.setBackground(new java.awt.Color(248, 248, 249));
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        txtFuel.setBackground(new java.awt.Color(248, 248, 249));

        txtTransmission.setBackground(new java.awt.Color(248, 248, 249));

        lblStatus.setText("Status");

        jLabel2.setText("Comments");

        txtComments.setEnabled(false);
        txtComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommentsActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnPostComments.setText("Post Comments");
        btnPostComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostCommentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(lblCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lblFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAccidents)
                            .addComponent(lblMilesDriven)
                            .addComponent(lblCarCompany)
                            .addComponent(lblCostPrice)
                            .addComponent(lblTransmission)
                            .addComponent(lblStatus)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCarCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtAccidents, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtMilesDriven, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtSellPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtFuel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtTransmission, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtStatus)
                    .addComponent(txtComments))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPostComments)
                    .addComponent(btnSave))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReject)
                    .addComponent(btnApprove))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarCompany)
                            .addComponent(txtCarCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFuelType)
                            .addComponent(txtFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblTransmission))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccidents)
                            .addComponent(txtAccidents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMilesDriven, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblMilesDriven))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCostPrice)
                            .addComponent(txtSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReject)
                        .addComponent(btnPostComments, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addGap(333, 333, 333))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCarCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarCompanyActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCommentsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        myCase.setComments(txtComments.getText());
        myCase.setStatus("On Hold");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
         myCase.setStatus("Rejected");
         myCase.setComments("Due to market we are not proceeding.");

    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
         myCase.setStatus("Approved");
         myCase.setComments("Hope to see you again.");
         
         CustomersSeller custSeller = custSellerDirectory.getCustomersSeller().stream()
                    .filter(it -> it.getUniqueId().equals(myCase.getCarId()))
                    .findFirst() 
                    .orElse(null);
         custSeller.setSet("Sold");
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnPostCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostCommentsActionPerformed
        // TODO add your handling code here:
        txtComments.setEnabled(true);
    }//GEN-LAST:event_btnPostCommentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnPostComments;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAccidents;
    private javax.swing.JLabel lblCarCompany;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCostPrice;
    private javax.swing.JLabel lblFuelType;
    private javax.swing.JLabel lblMilesDriven;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTransmission;
    private javax.swing.JTextField txtAccidents;
    private javax.swing.JTextField txtCarCompany;
    private javax.swing.JTextField txtComments;
    private javax.swing.JTextField txtFuel;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtMilesDriven;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSellPrice;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTransmission;
    // End of variables declaration//GEN-END:variables

    private void showDetailsofCase() {
        
        CustomersSeller custSeller = custSellerDirectory.getCustomersSeller().stream()
                    .filter(it -> it.getUniqueId().equals(myCase.getCarId()))
                    .findFirst() 
                    .orElse(null);
        
                System.out.println("c1 sell price "+custSeller.getSellingPrice());

            
        txtModel.setText(custSeller.getCarModel());
        txtManufactureYear.setText(custSeller.getManufacteryear());
        txtMilesDriven.setText(custSeller.getKmsDriven());
        txtFuel.setText(custSeller.getFuelType());
        txtTransmission.setText(custSeller.getTransmission());
        txtAccidents.setText(custSeller.getNoOfAccidents());
        txtCarCompany.setText(custSeller.getCarCompany());
        txtSellPrice.setText(custSeller.getSellingPrice());
        imgLogo.setIcon(custSeller.getLogoImage());
        txtStatus.setText(myCase.getStatus());
        txtComments.setText(myCase.getComments());
    }
}
