/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Business.Business;
import Business.Customers.CustomersBuyer;
import Business.Customers.CustomersBuyerDirectory;
import Business.Customers.CustomersSeller;
import Business.Customers.CustomersSellerDirectory;
import Business.UserAccountManagement.UserAccount;
import Utility.ImageTableCellRenderer;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bindupagad
 */
public class BuyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyJPanel
     */
    JPanel workAreaMain;
    Business business;
    UserAccount userAcc;
    CustomersBuyerDirectory custBuyerDirectory;
    CustomersSellerDirectory custDirectory;
    
    
    public BuyJPanel(JPanel workAreaMain, Business business, UserAccount userAcc) {
        initComponents();
        this.workAreaMain = workAreaMain;
        this.business = business;
        this.userAcc = userAcc;
        custBuyerDirectory = business.getCustBuyerDirectory();
        custDirectory = business.getCustomersSellerDirectory();
        loadCarTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarBuy = new javax.swing.JTable();
        btnInterested = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        txtManufactureYear = new javax.swing.JTextField();
        lblTransmission = new javax.swing.JLabel();
        lblMilesDriven = new javax.swing.JLabel();
        cmbTransmission = new javax.swing.JComboBox<>();
        lblFuelType = new javax.swing.JLabel();
        cmbFuelType = new javax.swing.JComboBox<>();
        txtMilesDriven = new javax.swing.JTextField();
        lblAccidents = new javax.swing.JLabel();
        txtCarCompany = new javax.swing.JTextField();
        txtAccidents = new javax.swing.JTextField();
        lblCarCompany = new javax.swing.JLabel();
        lblCostPrice = new javax.swing.JLabel();
        txtSellPrice = new javax.swing.JTextField();
        lblCarModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        btnSeeMore = new javax.swing.JButton();

        tblCarBuy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CarId", "Company", "Model", "Year of Making", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarBuy);

        btnInterested.setText("Interested to buy");
        btnInterested.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterestedActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(73, 84, 90));
        jLabel9.setText("Manufacture Year");

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtManufactureYear.setBackground(new java.awt.Color(248, 248, 249));

        lblTransmission.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblTransmission.setForeground(new java.awt.Color(73, 84, 90));
        lblTransmission.setText("Transmission");

        lblMilesDriven.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblMilesDriven.setForeground(new java.awt.Color(73, 84, 90));
        lblMilesDriven.setText("Miles Driven");

        cmbTransmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Manual", "Automatic" }));

        lblFuelType.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblFuelType.setForeground(new java.awt.Color(73, 84, 90));
        lblFuelType.setText("Fuel Type");

        cmbFuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Petrol", "Diesel", "Electric" }));
        cmbFuelType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFuelTypeActionPerformed(evt);
            }
        });

        txtMilesDriven.setBackground(new java.awt.Color(248, 248, 249));

        lblAccidents.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblAccidents.setForeground(new java.awt.Color(73, 84, 90));
        lblAccidents.setText("No. of Accidents");

        txtCarCompany.setBackground(new java.awt.Color(248, 248, 249));
        txtCarCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarCompanyActionPerformed(evt);
            }
        });

        txtAccidents.setBackground(new java.awt.Color(248, 248, 249));

        lblCarCompany.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblCarCompany.setForeground(new java.awt.Color(73, 84, 90));
        lblCarCompany.setText("Company");

        lblCostPrice.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblCostPrice.setForeground(new java.awt.Color(73, 84, 90));
        lblCostPrice.setText("Selling Price");

        txtSellPrice.setBackground(new java.awt.Color(248, 248, 249));

        lblCarModel.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblCarModel.setForeground(new java.awt.Color(73, 84, 90));
        lblCarModel.setText("Car Model");

        txtModel.setBackground(new java.awt.Color(248, 248, 249));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccidents)
                    .addComponent(lblMilesDriven)
                    .addComponent(lblCarCompany)
                    .addComponent(lblCostPrice)
                    .addComponent(lblTransmission))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCarCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccidents, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMilesDriven, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarCompany)
                            .addComponent(txtCarCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFuelType)
                            .addComponent(cmbFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTransmission)
                            .addComponent(cmbTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccidents)
                            .addComponent(txtAccidents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMilesDriven, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblMilesDriven))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCostPrice)
                            .addComponent(txtSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86))
        );

        btnSeeMore.setText("See more details");
        btnSeeMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeMoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeeMore)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnInterested)
                        .addGap(140, 140, 140))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeeMore))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btnInterested))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFuelTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFuelTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFuelTypeActionPerformed

    private void txtCarCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarCompanyActionPerformed

    private void btnInterestedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterestedActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCarBuy.getSelectedRow();
        
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the car buy");
        } 
      
    }//GEN-LAST:event_btnInterestedActionPerformed

    private void btnSeeMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeMoreActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tblCarBuy.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tblCarBuy.getModel();
        
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the car to see more details");
        }

      String carId = (String) model.getValueAt(selectedRowIndex, 0);
        
        System.out.println("carId "+carId);
        
            CustomersSeller custSeller = custDirectory.getCustomersSeller().stream()
                    .filter(it -> it.getUniqueId().equals(carId))
                    .findFirst() 
                    .orElse(null);
            
            ImageIcon logoImage = new ImageIcon(custSeller.getLogoImage().getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
            
        txtModel.setText(custSeller.getCarModel());
        txtManufactureYear.setText(custSeller.getManufacteryear());
        txtMilesDriven.setText(custSeller.getKmsDriven());
        cmbFuelType.setSelectedItem(custSeller.getFuelType());
        cmbTransmission.setSelectedItem(custSeller.getTransmission());
        txtAccidents.setText(custSeller.getNoOfAccidents());
        txtCarCompany.setText(custSeller.getCarCompany());
        txtSellPrice.setText(custSeller.getSellingPrice());
        imgLogo.setIcon(logoImage);
    }//GEN-LAST:event_btnSeeMoreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInterested;
    private javax.swing.JButton btnSeeMore;
    private javax.swing.JComboBox<String> cmbFuelType;
    private javax.swing.JComboBox<String> cmbTransmission;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccidents;
    private javax.swing.JLabel lblCarCompany;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCostPrice;
    private javax.swing.JLabel lblFuelType;
    private javax.swing.JLabel lblMilesDriven;
    private javax.swing.JLabel lblTransmission;
    private javax.swing.JTable tblCarBuy;
    private javax.swing.JTextField txtAccidents;
    private javax.swing.JTextField txtCarCompany;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtMilesDriven;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSellPrice;
    // End of variables declaration//GEN-END:variables

    private void loadCarTable() {
        DefaultTableModel model = (DefaultTableModel)tblCarBuy.getModel();
        model.setRowCount(0);
        
        Dimension desiredImageSize = new Dimension(2, 2);
       
        tblCarBuy.getColumnModel().getColumn(4).setCellRenderer(new ImageTableCellRenderer(desiredImageSize));

        for (CustomersSeller c : custDirectory.getCustomersSeller()) {
            Object row[] = new Object[5];
            if(c.getType() == "Sold"){
            row[0] = c.getUniqueId();
            row[1] = c.getCarCompany();
            row[2] = c.getCarModel();
            row[3] = c.getManufacteryear();
            row[4] = c.getLogoImage();
            model.addRow(row);
            }
           
        }                 
    }
      
       
}
