/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Business.Business;
import Business.Customers.CustomersSeller;
import Business.Customers.CustomersSellerDirectory;
import Business.Organizations.Technology;
import Business.Organizations.TechnologyDirectory;
import Business.UserAccountManagement.UserAccount;
import java.awt.Image;
import java.io.File;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Vijeth S
 */
public class SellJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellJPanel
     */
    JPanel workAreaMain;
    Business business;
    CustomersSellerDirectory custDirectory;
    UserAccount userAcc;

    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon logoImage;

    public SellJPanel(JPanel workAreaMain, Business business, UserAccount userAcc) {
        initComponents();
        this.workAreaMain = workAreaMain;
        this.business = business;
        this.userAcc = userAcc;
        custDirectory = business.getCustomersSellerDirectory();

        FileFilter jpegFilter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
        FileFilter pngFilter = new FileNameExtensionFilter("PNG file", "png", "png");

        fileChooser.addChoosableFileFilter(jpegFilter);
        fileChooser.addChoosableFileFilter(pngFilter);
        fileChooser.setFileFilter(pngFilter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        lblCarModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtManufactureYear = new javax.swing.JTextField();
        lblFuelType = new javax.swing.JLabel();
        lblTransmission = new javax.swing.JLabel();
        cmbTransmission = new javax.swing.JComboBox<>();
        cmbFuelType = new javax.swing.JComboBox<>();
        lblAccidents = new javax.swing.JLabel();
        txtAccidents = new javax.swing.JTextField();
        imgLogo = new javax.swing.JLabel();
        btnAttach = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        lblAccidents1 = new javax.swing.JLabel();
        lblMilesDriven = new javax.swing.JLabel();
        txtMilesDriven = new javax.swing.JTextField();
        txtCarCompany = new javax.swing.JTextField();
        lblCarCompany = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblCostPrice = new javax.swing.JLabel();
        txtSellPrice = new javax.swing.JTextField();

        btnLogout.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 51, 51));
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), null));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        setPreferredSize(new java.awt.Dimension(745, 650));

        lblCarModel.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblCarModel.setForeground(new java.awt.Color(73, 84, 90));
        lblCarModel.setText("Car Model");

        txtModel.setBackground(new java.awt.Color(248, 248, 249));

        jLabel9.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(73, 84, 90));
        jLabel9.setText("Manufacture Year");

        txtManufactureYear.setBackground(new java.awt.Color(248, 248, 249));

        lblFuelType.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblFuelType.setForeground(new java.awt.Color(73, 84, 90));
        lblFuelType.setText("Fuel Type");

        lblTransmission.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblTransmission.setForeground(new java.awt.Color(73, 84, 90));
        lblTransmission.setText("Transmission");

        cmbTransmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Manual", "Automatic" }));

        cmbFuelType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Petrol", "Diesel", "Electric" }));
        cmbFuelType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFuelTypeActionPerformed(evt);
            }
        });

        lblAccidents.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblAccidents.setForeground(new java.awt.Color(73, 84, 90));
        lblAccidents.setText("No. of Accidents");

        txtAccidents.setBackground(new java.awt.Color(248, 248, 249));

        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        lblAccidents1.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblAccidents1.setForeground(new java.awt.Color(73, 84, 90));
        lblAccidents1.setText("Upload Image");

        lblMilesDriven.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblMilesDriven.setForeground(new java.awt.Color(73, 84, 90));
        lblMilesDriven.setText("Miles Driven");

        txtMilesDriven.setBackground(new java.awt.Color(248, 248, 249));

        txtCarCompany.setBackground(new java.awt.Color(248, 248, 249));
        txtCarCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarCompanyActionPerformed(evt);
            }
        });

        lblCarCompany.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblCarCompany.setForeground(new java.awt.Color(73, 84, 90));
        lblCarCompany.setText("Company");

        btnSubmit.setText("Submit Quote");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblCostPrice.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lblCostPrice.setForeground(new java.awt.Color(73, 84, 90));
        lblCostPrice.setText("Selling Price");

        txtSellPrice.setBackground(new java.awt.Color(248, 248, 249));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTransmission)
                    .addComponent(lblAccidents)
                    .addComponent(lblCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMilesDriven)
                    .addComponent(lblCarCompany)
                    .addComponent(lblAccidents1)
                    .addComponent(lblCostPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccidents, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMilesDriven, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnRemove)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarCompany)
                    .addComponent(txtCarCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtManufactureYear))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFuelType)
                    .addComponent(cmbFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTransmission)
                    .addComponent(cmbTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccidents)
                    .addComponent(txtAccidents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMilesDriven)
                    .addComponent(txtMilesDriven, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostPrice)
                    .addComponent(txtSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccidents1)
                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAttach)
                    .addComponent(btnRemove))
                .addGap(47, 47, 47)
                .addComponent(btnSubmit)
                .addGap(55, 55, 55))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtManufactureYear, txtModel});

    }// </editor-fold>//GEN-END:initComponents

    private void cmbFuelTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFuelTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFuelTypeActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            URL url;
            try {
                url = file.toURI().toURL();
                logoImage = new ImageIcon(url);
                logoImage = new ImageIcon(logoImage.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));

                imgLogo.setIcon(logoImage);
            } catch (MalformedURLException ex) {
                //Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
       

    }//GEN-LAST:event_btnAttachActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        logoImage = null;
        imgLogo.setIcon(logoImage);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        workAreaMain.remove(this);
        ((java.awt.CardLayout) workAreaMain.getLayout()).next(workAreaMain);

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtCarCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarCompanyActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String carMod = txtModel.getText();
        String manufacteryear = txtManufactureYear.getText();
        String milesDriven = txtMilesDriven.getText();
        String fuelType = (String) cmbFuelType.getSelectedItem();
        String transmission = (String) cmbTransmission.getSelectedItem();
        String noOfAccidents = txtAccidents.getText();
        String carComp = txtCarCompany.getText();
        String sellPrice = txtSellPrice.getText();

        CustomersSeller c1 = new CustomersSeller(carMod, manufacteryear, milesDriven, fuelType, transmission, noOfAccidents, carComp, userAcc, sellPrice);
        c1.setLogoImage(logoImage);
        custDirectory.addCustomersSeller(c1);
        System.out.println("c1 sell price "+c1.getSellingPrice());

        JOptionPane.showMessageDialog(null, "Quote Submitted, agent will get in touch, track the progress in history tab.");
        
        txtModel.setText("");
        txtManufactureYear.setText("");
        txtMilesDriven.setText("");
        cmbFuelType.setSelectedItem("None");
        cmbTransmission.setSelectedItem("None");
        txtAccidents.setText("");
        txtCarCompany.setText("");
        txtSellPrice.setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbFuelType;
    private javax.swing.JComboBox<String> cmbTransmission;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAccidents;
    private javax.swing.JLabel lblAccidents1;
    private javax.swing.JLabel lblCarCompany;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCostPrice;
    private javax.swing.JLabel lblFuelType;
    private javax.swing.JLabel lblMilesDriven;
    private javax.swing.JLabel lblTransmission;
    private javax.swing.JTextField txtAccidents;
    private javax.swing.JTextField txtCarCompany;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtMilesDriven;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSellPrice;
    // End of variables declaration//GEN-END:variables
}
