/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Business.Business;
import Business.Customers.CustomersBuyer;
import Business.Customers.CustomersBuyerDirectory;
import Business.Customers.CustomersSeller;
import Business.Customers.CustomersSellerDirectory;
import Business.UserAccountManagement.UserAccount;
import Utility.ImageTableCellRenderer;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bindupagad
 */
public class AddCarsBuyRentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCarsBuyRentJPanel
     */
    JPanel workArea;
     Business business;
      CustomersSellerDirectory custSellerDirectory;
      CustomersBuyerDirectory custBuyerDirectory;
      DefaultTableModel model;
    public AddCarsBuyRentJPanel(JPanel workArea,Business business) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        custSellerDirectory = business.getCustomersSellerDirectory();
        custBuyerDirectory = business.getCustBuyerDirectory();
        loadCarTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarBuy = new javax.swing.JTable();
        lblInfo2 = new javax.swing.JLabel();
        txtBuyRent = new javax.swing.JComboBox<>();
        btnAddCatalog = new javax.swing.JButton();
        lblPriceChange = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();

        tblCarBuy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CarId", "Company", "Model", "Year of Making", "Selling Price", "Image"
            }
        ));
        jScrollPane1.setViewportView(tblCarBuy);

        lblInfo2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblInfo2.setText("Add to either Buy/Rent Catalog");
        lblInfo2.setEnabled(false);

        txtBuyRent.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        txtBuyRent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Buy", "Rent" }));
        txtBuyRent.setEnabled(false);
        txtBuyRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyRentActionPerformed(evt);
            }
        });

        btnAddCatalog.setText("Add");
        btnAddCatalog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatalogActionPerformed(evt);
            }
        });

        lblPriceChange.setText("Change Price");

        txtPrice.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPriceChange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInfo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuyRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfo2)
                    .addComponent(txtBuyRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPriceChange)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnAddCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuyRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuyRentActionPerformed

    CustomersSeller custSeller;
         UserAccount userAcc;
         String changePrice;
         String type;
         
    private void btnAddCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatalogActionPerformed
        // TODO add your handling code here:
        
         
         
        int selectedRowIndex = tblCarBuy.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the car from table to add to catalog");
            return;
        } 
        else {
             type = (String) model.getValueAt(selectedRowIndex, 3);
            String carId = (String) model.getValueAt(selectedRowIndex, 0);
             changePrice = txtPrice.getText();
            if (txtBuyRent.getSelectedItem() != "None") {
                type = (String) txtBuyRent.getSelectedItem();
                
                 custSeller = custSellerDirectory.getCustomersSeller().stream()
        .filter(it -> it.getUniqueId().equals(carId) )
        .findFirst()
        .orElse(null);
                
            } else {
                JOptionPane.showMessageDialog(this, "Please select a buy/rent from drop down.");
            }
            txtBuyRent.setSelectedItem("None");
        }
        String finalPrice;
        
        if(changePrice == null){
            finalPrice =  custSeller.getSellingPrice();
        }else{
            finalPrice = changePrice;
        }
        
        CustomersBuyer c1 = new CustomersBuyer(custSeller.getCarModel() , custSeller.getManufacteryear(), custSeller.getKmsDriven(), custSeller.getFuelType(), custSeller.getTransmission(), 
                custSeller.getCarCompany(), userAcc,finalPrice ,custSeller.getUniqueId(), type, "None");
        custBuyerDirectory.addCustomersBuyer(c1);
        
    }//GEN-LAST:event_btnAddCatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCatalog;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblPriceChange;
    private javax.swing.JTable tblCarBuy;
    private javax.swing.JComboBox<String> txtBuyRent;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    private void loadCarTable() {
        DefaultTableModel model = (DefaultTableModel)tblCarBuy.getModel();
        model.setRowCount(0);
        
        Dimension desiredImageSize = new Dimension(2, 2);
       
        tblCarBuy.getColumnModel().getColumn(4).setCellRenderer(new ImageTableCellRenderer(desiredImageSize));

        for (CustomersSeller c : custSellerDirectory.getCustomersSeller()) {
            Object row[] = new Object[5];
            if(c.getType() == "Sold"){
            row[0] = c.getUniqueId();
            row[1] = c.getCarCompany();
            row[2] = c.getCarModel();
            row[3] = c.getManufacteryear();
            row[4] = c.getLogoImage();
            model.addRow(row);
            }
           
        }
        
    }
}
