/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bindupagad
 */
public class AdminMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminMainJPanel
     */
    JPanel workAreaMain;
    Business business;

    public AdminMainJPanel(JPanel workAreaMain, Business business) {
        initComponents();
        this.workAreaMain = workAreaMain;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPane = new javax.swing.JPanel();
        btnAddExecutives = new javax.swing.JButton();
        btnCars = new javax.swing.JButton();
        btnInsurance = new javax.swing.JButton();
        btnTechnology = new javax.swing.JButton();
        btnSpareparts = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        btnAddExecutives.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        btnAddExecutives.setForeground(new java.awt.Color(255, 51, 51));
        btnAddExecutives.setText("Add Executives");
        btnAddExecutives.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), null));
        btnAddExecutives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExecutivesActionPerformed(evt);
            }
        });

        btnCars.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        btnCars.setForeground(new java.awt.Color(255, 51, 51));
        btnCars.setText("Add Cars to Rent/Buy");
        btnCars.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), null));
        btnCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarsActionPerformed(evt);
            }
        });

        btnInsurance.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        btnInsurance.setForeground(new java.awt.Color(255, 51, 51));
        btnInsurance.setText("Buy Insurance");
        btnInsurance.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), null));
        btnInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsuranceActionPerformed(evt);
            }
        });

        btnTechnology.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        btnTechnology.setForeground(new java.awt.Color(255, 51, 51));
        btnTechnology.setText("Buy Technology");
        btnTechnology.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), null));
        btnTechnology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTechnologyActionPerformed(evt);
            }
        });

        btnSpareparts.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        btnSpareparts.setForeground(new java.awt.Color(255, 51, 51));
        btnSpareparts.setText("Buy Spare-parts");
        btnSpareparts.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), null));
        btnSpareparts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparepartsActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 51, 51));
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), null));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPaneLayout = new javax.swing.GroupLayout(controlPane);
        controlPane.setLayout(controlPaneLayout);
        controlPaneLayout.setHorizontalGroup(
            controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCars, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(btnAddExecutives, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsurance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTechnology, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSpareparts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPaneLayout.setVerticalGroup(
            controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPaneLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnAddExecutives, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCars, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTechnology, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSpareparts, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        controlPaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCars, btnInsurance, btnSpareparts, btnTechnology});

        jSplitPane1.setLeftComponent(controlPane);

        workArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddExecutivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExecutivesActionPerformed
        // TODO add your handling code here:
        NewAgentsJPanel agentsPanel = new NewAgentsJPanel(workArea, business);
        workArea.add(agentsPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAddExecutivesActionPerformed

    private void btnCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarsActionPerformed
        // TODO add your handling code here:
        AddCarsBuyRentJPanel rentBuyPanel = new AddCarsBuyRentJPanel(workArea, business);
        workArea.add(rentBuyPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnCarsActionPerformed

    private void btnInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsuranceActionPerformed
        // TODO add your handling code here:
        InsurancesJPanel insurancePanel = new InsurancesJPanel(workArea, business);
        workArea.add(insurancePanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnInsuranceActionPerformed

    private void btnTechnologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTechnologyActionPerformed
        // TODO add your handling code here:
        TechnologiesJPanel techPanel = new TechnologiesJPanel(workArea, business);
        workArea.add(techPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnTechnologyActionPerformed

    private void btnSparepartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparepartsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSparepartsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        workAreaMain.remove(this);
        ((java.awt.CardLayout) workAreaMain.getLayout()).next(workAreaMain);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExecutives;
    private javax.swing.JButton btnCars;
    private javax.swing.JButton btnInsurance;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSpareparts;
    private javax.swing.JButton btnTechnology;
    private javax.swing.JPanel controlPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
