/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Business.Business;
import Business.Organizations.InsuranaceProvidersDirectory;
import Business.Organizations.InsuranceProviders;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bindupagad
 */
public class InsurancesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsurancesJPanel
     */
    JPanel workArea;
     Business business;
     InsuranaceProvidersDirectory insuranceHistory;
     List<InsuranceProviders> insuranceHistoryList;
     private Map<String, InsuranceProviders> insuranceProviderMap;
    
    public InsurancesJPanel(JPanel workArea,Business business) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        insuranceHistory = business.getInsuranceDirectory();
        insuranceHistoryList = insuranceHistory.getInsuranceProviders();
        
        insuranceProviderMap = new HashMap<>();
        for (InsuranceProviders provider : insuranceHistoryList) {
            insuranceProviderMap.put(provider.getInsuranceName(), provider);
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLiberty = new javax.swing.JButton();
        btnMapfre = new javax.swing.JButton();
        btnAmericanDream = new javax.swing.JButton();
        btnCompleteWarranty = new javax.swing.JButton();
        btnGoodStone = new javax.swing.JButton();
        btnEndurance = new javax.swing.JButton();
        txtPAPrice = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtRoadPrice = new javax.swing.JTextField();
        lblInsuranceName = new javax.swing.JLabel();
        lblRoadAssistance = new javax.swing.JLabel();
        lblAccidental = new javax.swing.JLabel();
        btnAddCatalogue = new javax.swing.JButton();
        lblAccidental1 = new javax.swing.JLabel();
        txtTheftPrice = new javax.swing.JTextField();
        lblPMonthly = new javax.swing.JLabel();
        txtPMPrice = new javax.swing.JTextField();
        lblPAnnual = new javax.swing.JLabel();
        txtAccidentalPrice = new javax.swing.JTextField();

        btnLiberty.setIcon(new javax.swing.ImageIcon("/Users/bindupagad/Documents/ProfilePic.jpeg")); // NOI18N
        btnLiberty.setText("Liberty Mutual");
        btnLiberty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibertyActionPerformed(evt);
            }
        });

        btnMapfre.setIcon(new javax.swing.ImageIcon("/Users/bindupagad/Documents/ProfilePic.jpeg")); // NOI18N
        btnMapfre.setText("MAPFRE");
        btnMapfre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapfreActionPerformed(evt);
            }
        });

        btnAmericanDream.setIcon(new javax.swing.ImageIcon("/Users/bindupagad/Documents/ProfilePic.jpeg")); // NOI18N
        btnAmericanDream.setText("American Dream");
        btnAmericanDream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmericanDreamActionPerformed(evt);
            }
        });

        btnCompleteWarranty.setIcon(new javax.swing.ImageIcon("/Users/bindupagad/Documents/ProfilePic.jpeg")); // NOI18N
        btnCompleteWarranty.setText("Complete Warranty");
        btnCompleteWarranty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteWarrantyActionPerformed(evt);
            }
        });

        btnGoodStone.setIcon(new javax.swing.ImageIcon("/Users/bindupagad/Documents/ProfilePic.jpeg")); // NOI18N
        btnGoodStone.setText("    Good Stone");
        btnGoodStone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoodStoneActionPerformed(evt);
            }
        });

        btnEndurance.setIcon(new javax.swing.ImageIcon("/Users/bindupagad/Documents/ProfilePic.jpeg")); // NOI18N
        btnEndurance.setText("Endurance");
        btnEndurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnduranceActionPerformed(evt);
            }
        });

        lblPrice.setText("Price");

        lblInsuranceName.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblInsuranceName.setText("Insurance Name");

        lblRoadAssistance.setText("Road Assistance");

        lblAccidental.setText("Accidental Damage ");

        btnAddCatalogue.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        btnAddCatalogue.setForeground(new java.awt.Color(255, 51, 51));
        btnAddCatalogue.setText("Add to Catalog");
        btnAddCatalogue.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), null));
        btnAddCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatalogueActionPerformed(evt);
            }
        });

        lblAccidental1.setText("Theft");

        lblPMonthly.setText("Premium Monthly");

        lblPAnnual.setText("Premium Annually");

        txtAccidentalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccidentalPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCompleteWarranty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAmericanDream, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnGoodStone, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLiberty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEndurance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMapfre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAccidental)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))
                                    .addComponent(txtAccidentalPrice)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnAddCatalogue, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPAnnual)
                                    .addGap(19, 19, 19)
                                    .addComponent(txtPAPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPMonthly)
                                    .addGap(22, 22, 22)
                                    .addComponent(txtPMPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblRoadAssistance, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRoadPrice))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblAccidental1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTheftPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(211, 211, 211))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInsuranceName)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAmericanDream, btnGoodStone});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAccidental, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(txtAccidentalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAccidental1)
                            .addComponent(txtTheftPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRoadAssistance)
                            .addComponent(txtRoadPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPMonthly)
                            .addComponent(txtPMPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(lblPAnnual))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(txtPAPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(btnAddCatalogue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAmericanDream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInsuranceName)
                    .addComponent(btnEndurance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLiberty, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(btnGoodStone, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompleteWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMapfre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAmericanDream, btnGoodStone});

    }// </editor-fold>//GEN-END:initComponents

    private void btnLibertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibertyActionPerformed
        // TODO add your handling code here:
        InsuranceProviders insurance = insuranceProviderMap.get("Liberty Mutual");
        lblInsuranceName.setText(insurance.getInsuranceName());
        txtAccidentalPrice.setText(insurance.getAccidentaldamagePrice());
        txtTheftPrice.setText(insurance.getTheftPrice());
        txtPMPrice.setText(insurance.getPremimumPMPrice());
        txtPAPrice.setText(insurance.getPremimumAnnualPrice());
        txtRoadPrice.setText(insurance.getRoadAssistancePrice());
    }//GEN-LAST:event_btnLibertyActionPerformed

    private void btnMapfreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapfreActionPerformed
        // TODO add your handling code here:
        InsuranceProviders insurance = insuranceProviderMap.get("MAPFRE");
        lblInsuranceName.setText(insurance.getInsuranceName());
        txtAccidentalPrice.setText(insurance.getAccidentaldamagePrice());
        txtTheftPrice.setText(insurance.getTheftPrice());
        txtPMPrice.setText(insurance.getPremimumPMPrice());
        txtPAPrice.setText(insurance.getPremimumAnnualPrice());
        txtRoadPrice.setText(insurance.getRoadAssistancePrice());
    }//GEN-LAST:event_btnMapfreActionPerformed

    private void btnAmericanDreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmericanDreamActionPerformed
        // TODO add your handling code here:

        InsuranceProviders insurance = insuranceProviderMap.get("American Dream");
        lblInsuranceName.setText(insurance.getInsuranceName());
        txtAccidentalPrice.setText(insurance.getAccidentaldamagePrice());
        txtTheftPrice.setText(insurance.getTheftPrice());
        txtPMPrice.setText(insurance.getPremimumPMPrice());
        txtPAPrice.setText(insurance.getPremimumAnnualPrice());
        txtRoadPrice.setText(insurance.getRoadAssistancePrice());

    }//GEN-LAST:event_btnAmericanDreamActionPerformed

    private void btnCompleteWarrantyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteWarrantyActionPerformed
        // TODO add your handling code here:
        InsuranceProviders insurance = insuranceProviderMap.get("Complete Warranty");
        lblInsuranceName.setText(insurance.getInsuranceName());
        txtAccidentalPrice.setText(insurance.getAccidentaldamagePrice());
        txtTheftPrice.setText(insurance.getTheftPrice());
        txtPMPrice.setText(insurance.getPremimumPMPrice());
        txtPAPrice.setText(insurance.getPremimumAnnualPrice());
        txtRoadPrice.setText(insurance.getRoadAssistancePrice());
    }//GEN-LAST:event_btnCompleteWarrantyActionPerformed

    private void btnGoodStoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoodStoneActionPerformed
        // TODO add your handling code here:
        InsuranceProviders insurance = insuranceProviderMap.get("Good Stone");
        lblInsuranceName.setText(insurance.getInsuranceName());
        txtAccidentalPrice.setText(insurance.getAccidentaldamagePrice());
        txtTheftPrice.setText(insurance.getTheftPrice());
        txtPMPrice.setText(insurance.getPremimumPMPrice());
        txtPAPrice.setText(insurance.getPremimumAnnualPrice());
        txtRoadPrice.setText(insurance.getRoadAssistancePrice());
    }//GEN-LAST:event_btnGoodStoneActionPerformed

    private void btnEnduranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnduranceActionPerformed
        // TODO add your handling code here:
        InsuranceProviders insurance = insuranceProviderMap.get("Endurance");
        lblInsuranceName.setText(insurance.getInsuranceName());
        txtAccidentalPrice.setText(insurance.getAccidentaldamagePrice());
        txtTheftPrice.setText(insurance.getTheftPrice());
        txtPMPrice.setText(insurance.getPremimumPMPrice());
        txtPAPrice.setText(insurance.getPremimumAnnualPrice());
        txtRoadPrice.setText(insurance.getRoadAssistancePrice());
    }//GEN-LAST:event_btnEnduranceActionPerformed

    private void btnAddCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatalogueActionPerformed
        // TODO add your handling code here:
        InsuranceProviders insurance = insuranceProviderMap.get(lblInsuranceName.getText());
        System.out.println("Catalog"+insurance.getAddedToCatalog());
        insurance.setAddedToCatalog("Yes");
        System.out.println("Catalog"+insurance.getAddedToCatalog());

        JOptionPane.showMessageDialog(null, "Insurance added to catalog!");

    }//GEN-LAST:event_btnAddCatalogueActionPerformed

    private void txtAccidentalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccidentalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccidentalPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCatalogue;
    private javax.swing.JButton btnAmericanDream;
    private javax.swing.JButton btnCompleteWarranty;
    private javax.swing.JButton btnEndurance;
    private javax.swing.JButton btnGoodStone;
    private javax.swing.JButton btnLiberty;
    private javax.swing.JButton btnMapfre;
    private javax.swing.JLabel lblAccidental;
    private javax.swing.JLabel lblAccidental1;
    private javax.swing.JLabel lblInsuranceName;
    private javax.swing.JLabel lblPAnnual;
    private javax.swing.JLabel lblPMonthly;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRoadAssistance;
    private javax.swing.JTextField txtAccidentalPrice;
    private javax.swing.JTextField txtPAPrice;
    private javax.swing.JTextField txtPMPrice;
    private javax.swing.JTextField txtRoadPrice;
    private javax.swing.JTextField txtTheftPrice;
    // End of variables declaration//GEN-END:variables
}
