/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Business.Business;
import Business.Roles.Roles;
import Business.User.User;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static Business.Roles.Roles.TypeOfRole.Executive;

/**
 *
 * @author bindupagad
 */
public class NewAgentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewAgentsJPanel
     */
     JPanel workArea;
     Business business;
     
     public static final Pattern EMAIL_REGEX
            = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
 
    public NewAgentsJPanel(JPanel workArea,Business business) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgentFirstName = new javax.swing.JLabel();
        txtAgentFirstName = new javax.swing.JTextField();
        lblAgentusername = new javax.swing.JLabel();
        txtAgentUsername = new javax.swing.JTextField();
        lblAgentPassword = new javax.swing.JLabel();
        txtAgentPassword = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtAgentLastName = new javax.swing.JTextField();
        lblAgentName1 = new javax.swing.JLabel();
        txtAgentEmail = new javax.swing.JTextField();
        lblAgentEmail = new javax.swing.JLabel();
        lblAgentEmail1 = new javax.swing.JLabel();
        txtAgentPhoneNum = new javax.swing.JTextField();
        lblAgentDetails = new javax.swing.JLabel();

        lblAgentFirstName.setText("Firstname");

        lblAgentusername.setText("Username");

        lblAgentPassword.setText("Password");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblAgentName1.setText("Lastname");

        lblAgentEmail.setText("Email");

        lblAgentEmail1.setText("Phone Number");

        lblAgentDetails.setText("Agent Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgentPassword)
                            .addComponent(lblAgentusername))
                        .addGap(96, 96, 96)
                        .addComponent(txtAgentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSave)
                        .addComponent(txtAgentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgentName1)
                            .addComponent(lblAgentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgentEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgentFirstName))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAgentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAgentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAgentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAgentPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAgentDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblAgentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgentFirstName)
                    .addComponent(txtAgentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgentName1)
                    .addComponent(txtAgentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgentEmail)
                    .addComponent(txtAgentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgentEmail1)
                    .addComponent(txtAgentPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentusername)
                    .addComponent(txtAgentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentPassword)
                    .addComponent(txtAgentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         if(txtAgentFirstName.getText().isEmpty() || txtAgentUsername.getText().isEmpty() || txtAgentPassword.getText().isEmpty() || txtAgentLastName.getText().isEmpty() || txtAgentEmail.getText().isEmpty() || txtAgentPhoneNum.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        } 
        if(business.getUserAccDirectory().checkIfUsernameIsUnique(txtAgentUsername.getText())){
            if(!txtAgentPhoneNum.getText().matches("[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"))
            {
                JOptionPane.showMessageDialog(null, " 10 digit phone number");
                txtAgentPhoneNum.setText("");
                return;
            }
            if (!EMAIL_REGEX.matcher(txtAgentEmail.getText()).matches()) {
                JOptionPane.showMessageDialog(null, "Please enter valid email address!!");
                txtAgentEmail.setText("");
                return;
            }
            
            if(!txtAgentPassword.getText().matches("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$"))
            {
                 JOptionPane.showMessageDialog(null, "Password is in incorrect \nFormat. Should be minimum 8 in length "
                    + "with one upper case, one lower case, one digit and one special character");
                txtAgentPassword.setText("");
                return;
            }
            
            User customer = new User(txtAgentFirstName.getText(),txtAgentLastName.getText(), txtAgentEmail.getText(),txtAgentPhoneNum.getText(),txtAgentUsername.getText(),txtAgentPassword.getText(), "Agent");
            business.getUserAccDirectory().addAccount(customer);
           
            txtAgentUsername.setText("");
            txtAgentEmail.setText("");
            txtAgentFirstName.setText("");
            txtAgentLastName.setText("");
            txtAgentPhoneNum.setText("");
            txtAgentPassword.setText("");
            JOptionPane.showMessageDialog(null, "User Account Created!!");
            
            
         }else{
            JOptionPane.showMessageDialog(null, "Username " + txtAgentUsername.getText() + " already exists !!!, Please try a new one");
         }
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAgentDetails;
    private javax.swing.JLabel lblAgentEmail;
    private javax.swing.JLabel lblAgentEmail1;
    private javax.swing.JLabel lblAgentFirstName;
    private javax.swing.JLabel lblAgentName1;
    private javax.swing.JLabel lblAgentPassword;
    private javax.swing.JLabel lblAgentusername;
    private javax.swing.JTextField txtAgentEmail;
    private javax.swing.JTextField txtAgentFirstName;
    private javax.swing.JTextField txtAgentLastName;
    private javax.swing.JTextField txtAgentPassword;
    private javax.swing.JTextField txtAgentPhoneNum;
    private javax.swing.JTextField txtAgentUsername;
    // End of variables declaration//GEN-END:variables
}
