/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Business.Business;
import Business.Organizations.Technology;
import Business.Organizations.TechnologyDirectory;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bindupagad
 */
public class TechnologiesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TechnologiesJPanel
     */
    JPanel workArea;
     Business business;
     TechnologyDirectory techDirectory;
      List<Technology> techList;
      
      private Map<String, Technology> technologyListMap;
   
     public TechnologiesJPanel(JPanel workArea,Business business) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        techDirectory = business.getTechnologyDirectory();
        techList = techDirectory.getTechnologies();
        
        technologyListMap = new HashMap<>();
        for (Technology tech : techList) {
            technologyListMap.put(tech.getTechnologyName(), tech);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMemory = new javax.swing.JButton();
        btnAdas = new javax.swing.JButton();
        btnGPS = new javax.swing.JButton();
        btnAppleCar = new javax.swing.JButton();
        lblTechName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtTechPrice = new javax.swing.JTextField();
        btnAddCatalog = new javax.swing.JButton();

        btnMemory.setIcon(new javax.swing.ImageIcon("/Users/bindupagad/Documents/ProfilePic.jpeg")); // NOI18N
        btnMemory.setText("Memory Seats");
        btnMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryActionPerformed(evt);
            }
        });

        btnAdas.setIcon(new javax.swing.ImageIcon("/Users/bindupagad/Documents/ProfilePic.jpeg")); // NOI18N
        btnAdas.setText("Adas System");
        btnAdas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdasActionPerformed(evt);
            }
        });

        btnGPS.setIcon(new javax.swing.ImageIcon("/Users/bindupagad/Documents/ProfilePic.jpeg")); // NOI18N
        btnGPS.setText("GPS Tracking");
        btnGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGPSActionPerformed(evt);
            }
        });

        btnAppleCar.setIcon(new javax.swing.ImageIcon("/Users/bindupagad/Documents/ProfilePic.jpeg")); // NOI18N
        btnAppleCar.setText("Apple Car Play");
        btnAppleCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppleCarActionPerformed(evt);
            }
        });

        lblTechName.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblTechName.setText("Technology Name");

        lblPrice.setText("Price");

        btnAddCatalog.setText("Add to Catalog");
        btnAddCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdas, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGPS, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAppleCar, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTechName)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTechPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btnAddCatalog)))
                .addGap(68, 286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdas)
                    .addComponent(btnGPS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAppleCar)
                    .addComponent(btnMemory))
                .addGap(35, 35, 35)
                .addComponent(lblTechName)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTechPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddCatalog)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryActionPerformed
        // TODO add your handling code here:
        Technology tech = technologyListMap.get("Apple Car Play");
        lblTechName.setText(tech.getTechnologyName());
        txtTechPrice.setText(tech.getTechnologyPrice());

    }//GEN-LAST:event_btnMemoryActionPerformed

    private void btnAdasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdasActionPerformed
        // TODO add your handling code here:
        Technology tech = technologyListMap.get("Adas System");
        lblTechName.setText(tech.getTechnologyName());
        txtTechPrice.setText(tech.getTechnologyPrice());
    }//GEN-LAST:event_btnAdasActionPerformed

    private void btnGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGPSActionPerformed
        // TODO add your handling code here:
        Technology tech = technologyListMap.get("GPS Tracking");
        lblTechName.setText(tech.getTechnologyName());
        txtTechPrice.setText(tech.getTechnologyPrice());
    }//GEN-LAST:event_btnGPSActionPerformed

    private void btnAppleCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppleCarActionPerformed
        // TODO add your handling code here:
        Technology tech = technologyListMap.get("Apple Car Play");
        lblTechName.setText(tech.getTechnologyName());
        txtTechPrice.setText(tech.getTechnologyPrice());
        

    }//GEN-LAST:event_btnAppleCarActionPerformed

    private void btnAddCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatalogActionPerformed
        // TODO add your handling code here:
                Technology tech = technologyListMap.get(lblTechName.getText());
        tech.setAddedToCatalog("Yes");

        JOptionPane.showMessageDialog(null, "Technoloy system added to catalog!");
    }//GEN-LAST:event_btnAddCatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdas;
    private javax.swing.JButton btnAddCatalog;
    private javax.swing.JButton btnAppleCar;
    private javax.swing.JButton btnGPS;
    private javax.swing.JButton btnMemory;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTechName;
    private javax.swing.JTextField txtTechPrice;
    // End of variables declaration//GEN-END:variables
}
